### ISSUE TITLE
keep up with raml2html updates

### ISSUE THREAD

**Issue by iki** [walling/gulp-raml2html#12]
package.json still refers to raml2html-0.30.0 released half a year ago, but a lot changed since that and it's at 1.1.0 currently with changed API, see https://github.com/kevinrenskers/raml2html/blob/master/changelog.md

**Comment by iki** [comment]
a workaround is to just use current raml2html directly:
https://gist.github.com/iki/784ddd5ab33c1e1b726b
... that also solves #6

**Comment by kevinrenskers** [comment]
raml2html is now at 1.3.0. The API was changed in 1.0.0 and is now considered stable.
